version: '3.4'
services: 
    web:
        container_name: urlshortener-frontend-app
        working_dir: /app
        build:
            context: .
            target: 'develop-stage'
        ports:
            - '8080:8080'
        volumes:
            - '.:/app'
        command: ["npm", "run", "serve"]